### PR TITLE
Report count coverage rather then set and only run 4 threads at a time

### PR DESCRIPTION
**Pull request by wesleybalvanz-wf**
@Workiva/dtbackend

### CODE REVIEW

**Comment by alexandercampbell-wf** [comment]
+1
Just curious; what's the advantage of making this change?

**Comment by wesleybalvanz-wf** [comment]
@alexandercampbell-wf With this change we can not only see that a line is covered but also how many times it is covered, the hope is we can start identifying areas that we have a lot of test duplication and remove some duplicates to speed up our test runs.

**Comment by wesleybalvanz-wf** [comment]
@alexandercampbell-wf I made a small change to only run verbosely when generating XML because running verbosely causes some issues with go files that are expecting flags.

**Comment by rosshendrickson-wf** [comment]
+1

**Pull request merged**
