### PR TITLE
RED-4337 - Replace Travis CI with GitHub Actions

### PR DESCRIPTION
**Pull request by matthewbelisle-wf**
Replace Travis CI with GitHub Actions @wesleybalvanz-wf Miguel will have to add the `TWINE_USERNAME` and `TWINE_PASSWORD` secrets to the repo.

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by matthewbelisle-wf** [comment]
Travis build passed ✅

https://github.com/matthewbelisle-wf/goverge/actions/runs/836254457

**Review by wesleybalvanz-wf — APPROVED** [review]
Looks good to me +1

**Comment by wesleybalvanz-wf** [comment]
> Travis build passed ✅
> 
> https://github.com/matthewbelisle-wf/goverge/actions/runs/836254457

You mean github actions build passed. 😉

**Comment by wesleybalvanz-wf** [comment]
@Workiva/release-management-p

**Comment by matthewbelisle-wf** [comment]
Ha, yeah thanks @wesleybalvanz-wf

**Comment by matthewbelisle-wf** [comment]
Waiting on https://jira.atl.workiva.net/browse/SAAS-9440

**Comment by matthewbelisle-wf** [comment]
@Workiva/release-management-p

**Comment by matthewbelisle-wf** [comment]
@Workiva/release-management-p

**Comment by matthewbelisle-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
